version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx3-compose
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./conf/juanma-davids.test.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web:/usr/share/nginx/html:ro
      - ./certs:/etc/nginx/certs:ro
